export const allPlatform = [
    {
      name: "Snapchat",
      url: "",
      initUrl: "https://www.snapchat.com/add/",
      svg: `/images/snapchat.svg`,
      placeholder: "Snapchat username",
    },
    {
      name: "YouTube",
      url: "",
      initUrl: "https://www.youtube.com/@",
      svg: `/images/youtube.svg`,
      placeholder: "YouTube link",
    },
    {
      name: "Instagram",
      url: "",
      initUrl: "https://www.instagram.com/",
      svg: "/images/instagram.svg",
      placeholder: "Instagram username",
    },
    {
      name: "WhatsApp",
      url: "",
      initUrl: "https://wa.me/91",
      svg: `/images/whatsapp.svg`,
      placeholder: "WhatsApp Number",
    },
    {
      name: "Amazon",
      url: "",
      initUrl: "",
      svg: `/images/amazon.svg`,
      placeholder: "Amozon Link",
    },
    {
      name: "TikTok",
      url: "",
      initUrl: "https://www.tiktok.com/@",
      svg: `/images/tiktok.svg`,
      placeholder: "Tiktok username",
    },
    {
      name: "X",
      url: "",
      initUrl: "https://x.com/",
      svg: `/images/x.svg`,
      placeholder: "X username",
    },
    {
      name: "SoundCloud",
      url: "",
      initUrl: "https://www.soundcloud.com/",
      svg: `/images/soundCloud.svg`,
      placeholder: "SoundCloud username",
    },
    {
      name: "Pinterest",
      url: "",
      initUrl: "https://www.pinterest.com/",
      svg: `/images/pinterest.svg`,
      placeholder: "Pinterest username",
    },
    {
      name: "Threads",
      url: "",
      initUrl: "https://www.threads.net/@",
      svg: `/images/threads.svg`,
      placeholder: "Thread username",
    },
    {
      name: "Calendly",
      url: "",
      initUrl: "https://calendly.com/",
      svg: `/images/calendly.svg`,
      placeholder: "Calendly username",
    },
    {
      name: "Depop",
      url: "",
      initUrl: "https://www.depop.com/",
      svg: `/images/depop.svg`,
      placeholder: "Depop username",
    },
    {
      name: "Github",
      url: "",
      initUrl: "https://github.com/",
      svg: `/images/github.svg`,
      placeholder: "Github username",
    },
    {
      name: "Facebook",
      url: "",
      initUrl: "https://www.facebook.com/",
      svg: `/images/facebook.svg`,
      placeholder: "Facebook username",
    },
    {
      name: "Spotify",
      url: "",
      initUrl: "",
      svg: `/images/spotify.svg`,
      placeholder: "Spotify username",
    },
    {
      name: "Skype",
      url: "",
      initUrl: "",
      svg: `/images/skype.svg`,
      placeholder: "Skype username",
    },
    {
      name: "Linkedin",
      url: "",
      initUrl: "",
      svg: `/images/linkedin.svg`,
      placeholder: "Linkedin username",
    },
  ];